import keyMirror from '../../lib/keyMirror';

export default keyMirror(
  'VIDEO_INIT',
  'VIDEO_LOAD_START',
  'VIDEO_PROGRESS',
  'VIDEO_SUSPEND',
  'VIDEO_ABORT',
  'VIDEO_ERROR',
  'VIDEO_EMPTIED',
  'VIDEO_STALLED',
  'VIDEO_LOADED_METADATA',
  'VIDEO_LOADED_DATA',
  'VIDEO_CAN_PLAY',
  'VIDEO_CAN_PLAY_THROUGH',
  'VIDEO_PLAYING',
  'VIDEO_WAITING',
  'VIDEO_SEEKING',
  'VIDEO_SEEKED',
  'VIDEO_ENDED',
  'VIDEO_DURATION_CHANGE',
  'VIDEO_TIME_UPDATE',
  'VIDEO_PLAY',
  'VIDEO_PAUSE',
  'VIDEO_RATE_CHANGE',
  'VIDEO_RESIZE',
  'VIDEO_VOLUME_CHANGE',
  'VIDEO_TOGGLE_LOOP'
);

export const error = ['VIDEO_ERROR', 'VIDEO_ABORT'];
export const networkState = [
  'VIDEO_INIT',
  'VIDEO_LOAD_START',
  'VIDEO_PROGRESS',
  'VIDEO_SUSPEND',
  'VIDEO_ABORT',
  'VIDEO_ERROR',
  'VIDEO_EMPTIED',
  'VIDEO_STALLED'
];

export const readyState = [
  'VIDEO_INIT',
  'VIDEO_LOADED_METADATA',
  'VIDEO_LOADED_DATA',
  'VIDEO_CAN_PLAY',
  'VIDEO_CAN_PLAY_THROUGH',
  'VIDEO_WAITING',
  'VIDEO_RESIZE'
];

export const time = [
  'VIDEO_SEEKING',
  'VIDEO_SEEKED',
  'VIDEO_ENDED',
  'VIDEO_TIME_UPDATE'
];
